### ISSUE TITLE
WHERE IS MENU?

### ISSUE THREAD

**Issue by LogoJorge** [Quantum-Manager/tracker#195] opened 2024-02-16 05:53 UTC
**Describe the bug**
When many folders have been created, the quntum menu is not known where it is, especially the order of images by date on the back (newest first) must be the default option enabled

**To Reproduce**
Create very much folders

**Expected behavior**

**Screenshots**

**System Information (please complete the following information):**
 - Extensions version [e.g. 1.0.0]
 - PHP version: [e.g. 7.2]
 - Server OS: [e.g. Linux/Windows]
 - Browser [e.g. firefox, chrome, safari, ie]

**Additional context**

**Comment by Sulpher** [comment] 2024-02-18 11:40
Your question is not clear because of non-correct grammar and terms you've used. Please use more simple phrases and try to use Google Translate/Deepl to translate it from your language into English.
And follow and prepare required information, not copy them as quote below.

_Expected behavior
A clear and concise description of what you expected to happen._

this is what you have to describe and do not keep this information as is.
Also you missed required information - Joomla and Quantum Manager versions.

**Comment by Sulpher** [comment] 2024-02-25 07:27
Well, A week has passed and no additional information was provided. I am closing this issue as non-actual.

**Closed as completed by Sulpher** 2024-02-25 07:27 UTC
Labels: bug
